# Nurikabe : Graphe et fonctions en Python

Ce document est écrit avec Notebook Jupyter.  
On peut représenter le Nurikabe en s'appuyant sur la théorie des graphes. La formualtion qui suit est basé selon la thèse de Bachelor de Johan Groenen, étudiant à l'université de Leiden.  
Ce document a pour but de montrer de manière simple certaines fonctions que nous avons utilisés dans notre algorithme. La lecture du code entier de notre programme pourrait être long et compliqué, c'est pourquoi ce document montre petit à petit comment marche certaines de nos fonctions.  
Ce document consiste en des reflexions sur le sujet mais ce document fait également office de terrain d'experimentation de Jupyter Notebook ainsi que du module NumPy.

### Représentation de la grille Nurikabe sous forme de graphe
Une grille d'un Nurikabe $m \times n$ peut être définie comme un graphe non-directionnel $G = (X, A)$ avec $X$ étant l'ensemble des sommets et $A$ étant l'ensemble des arêtes du graphe.

$$ X = \{(i, j)|i \in \{1, ..., m\}, j \in \{1, ..., n\}\} $$

$$ A = \{(a, b)|a, b \in X, adj(a, b)\} $$



$X$ représente toutes les cellules de la grille et $adj(a, b)$ est la relation d'adjacence entre deux cellules. Deux cellules $a = (i, j)$ et $b = (k, l)$ sont adjacents, indiqué par $adj(a, b)$, si

$$ |i - k| + |j - l| = 1 $$

## Représentation du Nurikabe en Python

Le code qui suit utilise le module NumPy. Nous n'avons pas utilisé NumPy dans notre programme car nous n'en avions pas connaissance cependant nous avons essayer de chercher et de comprendre comment l'utiliser. Le Nurikabe est représenté sous la forme d'un tableau à deux dimensions. NumPy permet justement de manipuler des tableaux avec des fonctions propre au module.  
Le code qui suit n'a pas été utilisé dans notre programme mais a été écrit a posteriori.

In [3]:
import numpy as np

In [4]:
P = np.array([[0, 0, 0, 0, 0],
              [6, 0, 2, 0, 0],
              [0, 0, 0, 0, 0],
              [0, 0, 2, 0, 2],
              [0, 0, 0, 0, 0]])

In [5]:
print(P)

[[0 0 0 0 0]
 [6 0 2 0 0]
 [0 0 0 0 0]
 [0 0 2 0 2]
 [0 0 0 0 0]]


La fonction numpy.array permet de créer un objet "array" de la table du Nurikabe. On pourra par la suite utiliser d'autre fonctions de NumPy sur ce tableau.  
"0" représente les cellules indéfinies.  

### Fonction indiquant l'adjacence de deux cellules :

In [9]:
def adj(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1

Exemples :

In [7]:
adj((0, 0), (0, 1))

True

In [8]:
adj((0, 0), (0, 2))

False

### Trouver l'indice des pivots

Un pivot correspond à la cellule d'une île qui contient un chiffre (taille de l'île) 

In [14]:
np.nonzero(P)

(array([1, 1, 3, 3]), array([0, 2, 2, 4]))

Ici, le résultat n'est pas encore convaincant.

In [12]:
np.transpose(np.nonzero(P))

array([[1, 0],
       [1, 2],
       [3, 2],
       [3, 4]])

De cette manière, on obtient une liste des indices des pivots. On peut créer une fonction qui nous retourne cette liste.

In [15]:
def pivot_index(P):
    return  np.transpose(np.nonzero(P))

In [16]:
pivot_index(P)

array([[1, 0],
       [1, 2],
       [3, 2],
       [3, 4]])